version: "3"

services:
    aria2:
        build: ./aria2
        volumes:
            - $HOME/Downloads/TD/aria2:/downloads
            - ./aria2/config:/etc/aria2
        ports:
            - "6800:6800"

    httpd:
        build: ./web_server
        volumes:
            - ./:/usr/html
        ports:
            - "8888:8888"
